name: "Cloud.gov CF CLI Tools"
description: "Deploy and manage apps on cloud.gov"
inputs:
  cf_api:
    description: "Target API endpoint. Defaults to api.fr.cloud.gov."
    required: false
  cf_username:
    description: "Username for API authentication"
    required: true
  cf_password:
    description: "Password for API authentication"
    required: true
  cf_org:
    description: "Target organization"
    required: false
  cf_space:
    description: "Target space"
    required: false
  cf_manifest:
    description: "Manifest file name"
    required: false
  cf_vars_file:
    description: "Name of the vars file to use"
    required: false
  cf_command:
    description: "CF CLI command to run"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
